version: '3.4'

volumes:
  cake.db.volume:
    name: cake.db.volume

services:
  nginx:
    image: nginx:1.17
    container_name: cake_nginx
    ports:
      - '8080:80'
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/htdocs:/var/www/html
    networks:
      vpcbr:
        ipv4_address: 172.30.0.2

  php:
    container_name: cake_php
    build: config/php
    volumes:
      - ./src/htdocs:/var/www/html
    networks:
      vpcbr:
        ipv4_address: 172.30.0.3

  db:
    image: mysql:5.7
    container_name: cake_db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: cake
      MYSQL_USER: myroot
      MYSQL_PASSWORD: mypass
      TZ: 'Asia/Tokyo'
    volumes:
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf
      - ./config/mysql/init:/docker-entrypoint-initdb.d
      - cake.db.volume:/var/lib/mysql
    networks:
      vpcbr:
        ipv4_address: 172.30.0.4

networks:
  vpcbr:
    ipam:
      driver: default
      config:
      - subnet: 172.30.0.0/16